# Generated by Django 2.1.1 on 2018-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('imdb_code', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('title_english', models.CharField(blank=True, max_length=200, null=True)),
                ('title_long', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=500)),
                ('description_full', models.CharField(blank=True, max_length=500, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=500, null=True)),
                ('yt_trailer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('mpa_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('background_image', models.URLField(blank=True, null=True)),
                ('background_image_original', models.URLField(blank=True, null=True)),
                ('small_cover_image', models.URLField(blank=True, null=True)),
                ('medium_cover_image', models.URLField(blank=True, null=True)),
                ('large_cover_image', models.URLField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('date_uploaded', models.DateTimeField(blank=True, null=True)),
                ('date_uploaded_unix', models.PositiveIntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=200, null=True)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('seeds', models.PositiveIntegerField(blank=True, null=True)),
                ('peers', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(blank=True, null=True)),
                ('date_uploaded_unix', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='torrents',
            field=models.ManyToManyField(blank=True, to='movies.Torrent'),
        ),
    ]
